### PR TITLE
PerunArt baseURI, idempotent token(type) registration, catch withdrawal reverts

### PR DESCRIPTION
**Pull request by sebastianst**
- PerunArt: Set baseURI in constructor
- lib/Bytes: Add areEqual(Str) functions for bytes/string equality check
- Erdstall: Make token (type) registration idempotent
- Erdstall: Catch individual token transfer exceptions during withdrawals
- test: Test reverts during withdrawals

### CODE REVIEW

**Comment by sebastianst** [comment]
Will extend the `tokenURI` to appends its own address to the `baseURI`.

**Review by RmbRT — DISMISSED** [review]
I almost died when I read that byte comparison function…

**Comment by sebastianst** [comment]
> I almost died when I read that byte comparison function…

Me too at first, but [it's the cheapest way to do it](https://fravoll.github.io/solidity-patterns/string_equality_comparison.html).

**Comment by sebastianst** [comment]
Added the contract address to the base URI. Note that it's the all lower-caps address, not the checksum hex as specified in [EIP 55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).

**Review by ndzik — DISMISSED** [review]
Solidity is hardcore.

**Review by RmbRT — APPROVED** [review]

**Pull request merged**
